version: "3.2"
services:
  # ----------------------------------------
  # WATCHTOWER
  # Automatic Update Service for Docker VMs
  # ----------------------------------------
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      #- WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/ssl/certs:/etc/ssl/certs"
    command: --schedule "0 0 6 * * ?" --cleanup

  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - NET_ADMIN # required to modify network interfaces
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - GROUPID=0 # default group id, for downloaded files access rights
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun # tun device
      - ${DOCKERCONFDIR}/vpn:/vpn # OpenVPN configuration
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
      - 1194:1194
      - 1198:1998
    command: "-r 172.19.0.0/16" # route local network traffic
    dns: 8.8.4.4

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always
    network_mode: service:vpn # run on the vpn network
    depends_on: 
      - vpn
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TZ} # timezone
    volumes:
      - ${DOCKERSTORAGEDIR}/torrents:/data/torrents # download folder
      - ${DOCKERCONFDIR}/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host # option only available on linux
    dns:
      - 8.8.8.8
      - 4.4.4.4
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TZ} # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERSTORAGEDIR}/torrents/torrent-blackhole:/data/torrents/torrent-blackhole
      - ${DOCKERCONFDIR}/jackett:/config # config files

  flaresolver:
    container_name: flaresolver
    image: flaresolverr/flaresolverr:latest
    network_mode: host
    environment:
      - TZ=${TZ}
    #volumes:
      #- ${DOCKERCONFDIR}/flaresolverr/flaresolverr_service.py:/app/flaresolverr_service.py
    restart: unless-stopped

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TZ} # timezone
    volumes:
      - ${DOCKERSTORAGEDIR}/usenet:/data/usenet:rw # download folder
      - ${DOCKERCONFDIR}/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host # option only available on linux
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TZ} # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sonarr:/config # config files
      - ${DOCKERSTORAGEDIR}:/data # tv shows folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host # option only available on linux
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TZ} # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/radarr:/config # config files
      - ${DOCKERSTORAGEDIR}:/data # movies folder

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    network_mode: host # option only available on linux
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/bazarr:/config
      - ${DOCKERSTORAGEDIR}/media:/data/media

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    #devices:
      #- /dev/dri/card0:/dev/dri/card0
      #- /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - TZ=${TZ} # timezone
    network_mode: host # option only available on linux
    volumes:
      - ${DOCKERCONFDIR}/plex/db:/config:rw # plex database
      - ${DOCKERCONFDIR}/plex/transcode:/transcode # temp transcoded files
      - ${DOCKERSTORAGEDIR}/media:/data/media:rw # media library
      - ${DOCKERSTORAGEDIR}/photo:/data/photo:rw

